name = "backend"
compatibility_date = "2024-09-30"
compatibility_flags = [ "nodejs_compat" ]

 [vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiZmE0MGVlYTAtNTgxNC00NDY0LTk2NzYtMmQxNzBhYmE4Y2ViIiwidGVuYW50X2lkIjoiNTU5Mjk3NGI5NjhjOWU1MjQ0YjZjNjlmZTc1MThjM2JmZmE2MjQ1ODk1ZGZiNDVkZDc2YjY2ZmRhMWM5ZjVjYyIsImludGVybmFsX3NlY3JldCI6ImQ4M2Y0YTgyLTM4NTQtNDI1Zi04YzlkLTU4MTg4ZjEwY2IzZiJ9.9-QFVRUGxAW7kwpipNWXVhTI5JiX_LdQZQM-OqU-_Dg"
JWT_SECRET="ashdjhs"


# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"